### ISSUE TITLE
Unable to run sz_website_simple.py

### ISSUE THREAD

**Issue by jrgx19** [ThePiHut/statusboard-statuszero-docs#6]
When trying to run the sample code on a Raspberrypi 4, I get the following errors:

```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 109, in pin
    pin = self.pins[n]
KeyError: 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 12, in <module>
    sz = StatusZero('raspberrypi', 'codeclub', 'coderdojo')
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 124, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/boards.py", line 1233, in __init__
    for (green, red), label in zip(pins, labels)
  File "/usr/lib/python3/dist-packages/gpiozero/boards.py", line 1233, in <dictcomp>
    for (green, red), label in zip(pins, labels)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 124, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/boards.py", line 415, in __init__
    super(LEDBoard, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/boards.py", line 335, in __init__
    for name, pin_or_collection in kwargs.items()
  File "/usr/lib/python3/dist-packages/gpiozero/boards.py", line 335, in <dictcomp>
    for name, pin_or_collection in kwargs.items()
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 124, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 211, in __init__
    pin, active_high, initial_value, pin_factory=pin_factory
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 93, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 106, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 521, in __init__
    pin = self.pin_factory.pin(pin)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 111, in pin
    pin = self.pin_class(self, n)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 132, in __init__
    GPIO.setup(self.number, GPIO.IN, self.GPIO_PULL_UPS[self._pull])
RuntimeError: Not running on a RPi!
```

**Comment by bennuttall** [comment]
Are you using Raspbian?
